version: "3.1"

services:


  app:
    container_name: app
    build: ./
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    command: npm run dev
    networks:
      - app-network
    restart: "always"
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      TOKEN_SECRET: 8789
      MONGODB_STRING: mongodb://admin:admin@mongo:27017/
      EMAIL_PASS:
      EMAIL_USER:
      USER_DAILY_LIMIT: 9999
      PAYPAL_CLIENT_ID:
      PAYPAL_CLIENT_SECRET:
      PAYPAL_USD_THREE_MONTHS: 4.99
      PAYPAL_USD_SIX_MONTHS: 14.99
      PAYPAL_USD_ONE_YEAR: 24.99
      PAYPAL_BRL_THREE_MONTHS: 24.99
      PAYPAL_BRL_SIX_MONTHS: 44.99
      PAYPAL_BRL_ONE_YEAR: 59.99
      TRIAL_DAYS: 9999
      
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
    - app-network


  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
    networks:
    - app-network  


networks:
  app-network:
    driver: bridge
